name: python_requirements_download

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      image:
        description: "langgenius/dify-sandbox:latest"
        required: true
        default: "langgenius/dify-sandbox:0.2.12"
      platform_arm:
        description: "Run on arm64 runner (true = arm64, false = amd64)"
        required: true
        default: "false"

jobs:
  download:
    runs-on: ${{ inputs.platform_arm == 'true' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: pull image
        run: |
          docker pull ${{ inputs.image }}

      - name: create whls directory
        run: mkdir -p ${{ github.workspace }}/artifact_root/whls

      - name: run container
        run: |
          docker run --rm --entrypoint "" -v ${{ github.workspace }}/artifact_root/whls:/whls -v ${{ github.workspace }}/python-requirements.txt:/data/python-requirements.txt ${{ inputs.image }} pip3 download -r /data/python-requirements.txt -d /whls

      - name: upload artifact
        uses: actions/upload-artifact@v4

        with:
          name: whls
          path: ${{ github.workspace }}/artifact_root
